// <auto-generated />
namespace SpaceDoctor.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_XExamsType_NN_XParamsType_relation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_XExamsType_NN_XParamsType_relation));
        
        string IMigrationMetadata.Id
        {
            get { return "201510261839302_Add_XExamsType_N-N_XParamsType_relation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
